name: school_dashboard
description: A professional school parent Flutter application
publish_to: 'none'
version: 3.1.13+25

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.5.0
  flutter_lints: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.5.0
  device_info_plus: ^12.2.0
  flutter_dotenv: ^6.0.0
  dio: ^5.9.0
  html: ^0.15.6
  url_launcher: ^6.3.2
  video_player: ^2.10.0
  youtube_player_flutter: ^9.1.3
  youtube_player_iframe: ^5.2.2
  photo_view: ^0.15.0
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  chewie: ^1.13.0
  just_audio: ^0.10.5
  audio_video_progress_bar: ^2.0.3
  rxdart: ^0.28.0
  table_calendar: ^3.2.0
  record: ^6.1.2
  audioplayers: ^6.5.1
  flutter_tts: ^4.2.3
  image_picker: ^1.2.0
  visibility_detector: ^0.4.0+2
  in_app_update: ^4.2.5
  flutter_launcher_icons: ^0.14.4
  auto_size_text: ^3.0.0
  flutter_html: ^3.0.0

  

  # For translation (English ↔ Tamil)
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true   # ✅ Must be here, at the root under flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/clasteqdemo-playstore.png"
  remove_alpha_ios: true
